title: "Amartya Chakrabortty"
email: amartya4381@gmail.com
description: "Researcher in PDEs, Continuum Mechanics, and Nonlinear Elasticity"
theme: jekyll-theme-slate
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jekyll

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
